name: 'Extract Pull Request Metadata'
description: 'Extract Pull Request Metadata'
author: 'Robert Wiesner'
branding:
  icon: 'check'
  color: 'green'
inputs:
  repo-token:
    description: 'Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}'
    required: true
  receiver-endpoint:
    description: 'REST Endpoint to receive the data. Can be passed in using {{ secrets.REST_ENDPOINT }}'
    required: true
      
    
runs:
  using: 'node12'
  main: 'lib/index.js'

