name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/auto-assign-review-teams@v0.0.6
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        persons: "rowi1de"
        teams: "no-team"
        include-draft: false
        skip-with-manual-reviewers: 1
        
