name: CI

on: [push, pull]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/action-extract-pull-metadata@master
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        receiver-endpoint: ${{ secrets.REST_ENDPOINT }}
        
