name: "self@action-extract-pull-metadata"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - run: npm ci
    - run: npm run build
    - run: npm test
    - uses: ./
      with: 
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        receiver-endpoint: ${{ secrets.REST_ENDPOINT }}
